/*
LoginWindow

17/04/2018
Ricky Kearney - 14141647
Piotr Kurzynoga - 14143097

This class creates a JFrame where the user can input login details.
Login details are passed to the web service API for validation:
If login is successful the user is passed to the menu
if the login fails the user is propted to reenter the details.

 */
package tictactoe;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

public class LoginWindow extends javax.swing.JFrame {

    private static int userCheck = 0; // holds the logged in users ID
    private static String usernameCheck = ""; // holds logged in users username

    /**
     * Creates new form Login
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        registerBn = new javax.swing.JButton();
        loginBn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        registerBn.setText("Register");
        registerBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBnActionPerformed(evt);
            }
        });

        loginBn.setText("Login");
        loginBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBnActionPerformed(evt);
            }
        });

        userMessage = new JLabel("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(83)
                                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(registerBn)
                                                                .addGap(18)
                                                                .addComponent(loginBn))
                                                        .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(usernameLabel)
                                                                        .addGap(18)
                                                                        .addComponent(usernameInput, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(passwordLabel)
                                                                        .addGap(18)
                                                                        .addComponent(passwordInput, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(128)
                                                .addComponent(userMessage)))
                                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26)
                                .addComponent(userMessage)
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(27)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(registerBn)
                                        .addComponent(loginBn))
                                .addContainerGap(134, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // register button action listener
    private void registerBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBnActionPerformed
        this.setVisible(false); // close this window
        RegisterWindow register = new RegisterWindow(); // open the register window
        register.show();
    }//GEN-LAST:event_registerBnActionPerformed

    // login button action listener
    private void loginBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBnActionPerformed
        String username = usernameInput.getText();
        String password = passwordInput.getText();

        TicTacToe game = new TicTacToe();
        TTTWebService myLink = game.getProxy();

        userCheck = myLink.login(username, password); // call the webservice and check user login details

        if (userCheck > 0) { // a valid login will have ID > 0
            System.out.println("User ID = " + userCheck); // print to console
            usernameCheck = username;
            this.setVisible(false);
            GameMenu games = new GameMenu(); // show menu
            games.getFrame().setVisible(true);
        } else {
            System.out.println("Login Unsuccessful");
        }

    }//GEN-LAST:event_loginBnActionPerformed

    // get the logged In users ID
    public static int getUser() {
        return userCheck;
    }

    // get the logged in users username
    public static String getUsername() {
        return usernameCheck;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton registerBn;
    private javax.swing.JButton loginBn;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JTextField passwordInput;
    private JLabel userMessage;
    // End of variables declaration//GEN-END:variables
}
