/*
Register window

17/04/2018
Ricky Kearney - 14141647
Piotr Kurzynoga - 14143097

This class creates the register window where a new user can make an account.
it takes in name, surname, username and password
If the login was successful the user is sent to the login window.
If the login was not successful they are prompted to reenter.


 */
package tictactoe;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author puser
 */
public class RegisterWindow extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public RegisterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nameInput = new javax.swing.JTextField();
        surnameInput = new javax.swing.JTextField();
        usernameInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        submitBn = new javax.swing.JButton();
        clearBn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameInput.setToolTipText("");
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        surnameLabel.setText("Surname");

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        submitBn.setText("Submit");
        submitBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBnActionPerformed(evt);
            }
        });

        clearBn.setText("Clear");
        clearBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBnActionPerformed(evt);
            }
        });

        userMessage = new JLabel("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(99, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                                                        .addComponent(nameLabel)
                                                                        .addComponent(surnameLabel)
                                                                        .addComponent(usernameLabel))
                                                                .addGap(71)
                                                                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                                                                        .addComponent(usernameInput, GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                                                        .addComponent(nameInput)
                                                                        .addComponent(surnameInput)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(passwordLabel)
                                                                .addGap(73)
                                                                .addComponent(passwordInput, GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                                                .addGap(126))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(clearBn)
                                                .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(submitBn)
                                                .addGap(118))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(165)
                                .addComponent(userMessage)
                                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14)
                                .addComponent(userMessage)
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(nameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameLabel))
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(surnameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(surnameLabel))
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(usernameInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameLabel))
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(passwordInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel))
                                .addPreferredGap(ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(submitBn)
                                        .addComponent(clearBn))
                                .addGap(28))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed

    }//GEN-LAST:event_nameInputActionPerformed

    // On submitted button click
    private void submitBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBnActionPerformed
        String name = nameInput.getText(); // get inputted data
        String surname = surnameInput.getText();
        String username = usernameInput.getText();
        String password = passwordInput.getText();
        String message = "";

        TicTacToe game = new TicTacToe();
        TTTWebService myLink = game.getProxy();
        String registerResult;
        int pid = 0; // user's ID
        registerResult = myLink.register(username, password, name, surname); // send details to the webservice
        try {
            pid = Integer.parseInt(registerResult); // try get the new users ID
        } catch (Exception e) { // catch any exception that is thrown by getting the user's ID from register result
            if (registerResult.equals("ERROR-REPEAT")) {
                System.out.println("ERROR-REPEAT");
                message = "ERROR-REPEAT";
            } else if (registerResult.equals("ERROR-INSERT")) {
                System.out.println("ERROR-INSERT");
                message = "ERROR-INSERT";
            } else if (registerResult.equals("ERROR-RETRIEVE")) {
                System.out.println("ERROR-RETRIEVE");
                message = "ERROR-RETRIEVE";
            } else if (registerResult.equals("ERROR-DB")) {
                System.out.println("ERROR-DB");
                message = "ERROR-DB";
            }
        }
        if (pid == 0) { // Not a valid new user ID
            message += " - Cannot create user";
        } else { // user successfully registered
            message = "User Registered";
            this.setVisible(false); // close this window
            LoginWindow login = new LoginWindow(); // open the login window where the user can login.
            login.show();
        }

        System.out.println(message); // print the result to console

    }//GEN-LAST:event_submitBnActionPerformed

    // clear button action listener
    private void clearBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBnActionPerformed
        nameInput.setText(""); // clear fields
        surnameInput.setText("");
        usernameInput.setText("");
        passwordInput.setText("");
    }//GEN-LAST:event_clearBnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1; // dont think this is used?
    private javax.swing.JButton submitBn;
    private javax.swing.JButton clearBn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userMessage;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField surnameInput;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JTextField passwordInput;
}
